name: PPUU_FW
channels:
  - pytorch
  - defaults
dependencies:
  - imageio
  - pandas
  - python=3.8
  - pytorch=1.5.1
  - scipy
  - matplotlib
  - pip
  - jupyter
  - scikit-learn
  - scikit-image
  - pip:
    - gym
    - pygame>=2.0.0.dev6
    - jupytext
    - ipdb
    - tb-nightly
    - moviepy
    - bqplot
    - astropy
